name: google_places_sdk_text_field_example
description: "Demonstrates how to use the google_places_sdk_text_field plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  google_places_sdk_text_field:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true